### PR TITLE
Naomimmm/update record

### PR DESCRIPTION
**Pull request by Naomimmm**

### CODE REVIEW

**Review by daedren30 — APPROVED** [review]
Tested and works well with valid inputs. We may want to add validation for all inputs but that may not be practical by the demo. Let's get it integrated and if we need to do little things later we can.

**Review by jcasta30 — APPROVED** [review]
Also tested it, looks and runs great! I also liked the format selection of your code. Maybe a thing to add in the future would be if the user enters an invalid order number to notify the user of the error.

**Comment by Naomimmm** [comment]
> Also tested it, looks and runs great! I also liked the format selection of your code. Maybe a thing to add in the future would be if the user enters an invalid order number to notify the user of the error.

Good point! I added this validation in this pull request https://github.com/SpilledCofee/DataBase/pull/66

**Comment by Naomimmm** [comment]
> Tested and works well with valid inputs. We may want to add validation for all inputs but that may not be practical by the demo. Let's get it integrated and if we need to do little things later we can.

Good point! I think Suthery's validation is really good. Maybe we can have his validations be their own methods and then we can reuse them in all of the methods as needed

**Comment by Naomimmm** [comment]
> > Also tested it, looks and runs great! I also liked the format selection of your code. Maybe a thing to add in the future would be if the user enters an invalid order number to notify the user of the error.
> 

@jcasta30  Good point! I added this validation in this pull request #66

**Pull request merged**
