### PR TITLE
Added Search GUI

### PR DESCRIPTION
**Pull request by Naomimmm**
Added GUI to use for searching the customer orders database.
Users can search by product id, order id, email address, customer zip code, and date.

It uses the template from search in our inventory database and queries the new customer order tables.

### CODE REVIEW

**Review by jblss888 — APPROVED** [review]
It look amazing! Great job

**Review by jtwardosz1 — APPROVED** [review]
LOOKS GREAT!!!!

**Review by ssok305 — APPROVED** [review]
Look great.

**Review by jcasta30 — APPROVED** [review]
Nice Job!

**Pull request merged**
