### PR TITLE
Jtwardosz1 view order update 2.0

### PR DESCRIPTION
**Pull request by jtwardosz1**
this should allow program to exit back to main menu when finished and once displayMenu() is called in main.

### CODE REVIEW

**Review by jcasta30 — COMMENTED** [review]
Code looks good! Although I have one question did you alter the customer's order CSV file? Because it says it you also made changes to it under "files changed"? or maybe added it again?

**Comment by jtwardosz1** [comment]
> Code looks good! Although I have one question did you alter the customer's order CSV file? Because it says it you also made changes to it under "files changed"? or maybe added it again?

So when I originally created the request I had left the custOrder.displayMenu() in the main but deleted that as it caused a conflict and that was obviously going to be added later. I assume that is what it is referencing but otherwise I made no changes to the CSV or anything like that.

**Review by jcasta30 — DISMISSED** [review]
oh ok, I'll approve it then. Although I'm not sure if anything will happen to the CSV file or if it will be added.

**Review by daedren30 — APPROVED** [review]
Approving after deleting the CSV file accidentally included

**Review by jcasta30 — APPROVED** [review]
Looks Good

**Pull request merged**
